### ISSUE TITLE
--set doesn't seem to be working

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/kubicorn#381]
Trying to tinker with the new `--set` flag

If I do

```bash
kubicorn create knova -p azure --set location=uswest
cat _state/knova/cluster.yaml | grep uswest
```

I get no results

**Comment by xmudrii** [comment]
@kris-nova IIRC `--set`‎ is implemented only for `apply` command. Flag exist for `create` as well but logic beside it isn't there.

Should be easy fix. I didn't have time last evening to thinker with it as it was quite late. ‎

**Comment by xmudrii** [comment]
Obviously I'm wrong. Will look into this. 
‎

**Comment by xmudrii** [comment]
@kris-nova it requires us to use names from Go Struct rather than from config file.
What does this means? In config file `_config.yaml`, field is called `location`, but in appropriate profile Go file, field is called `Location` (capital L).
If you use `kubicorn create knova -p azure --set Location=uswest` it would work.

I don't like this behavior, but I'm pretty much busy today. If nobody takes a look, I'll try to address it tomorrow.

**Comment by xmudrii** [comment]
Duplicate of #417
