### ISSUE TITLE
Implement go-prompt

### ISSUE THREAD

**Issue by MyDigitalLife** [kris-nova/kubicorn#399]
To make the Kubicorn experience even better we can implement [go-promp](https://github.com/c-bata/go-prompt). Basically it will add auto completion and some other fancy stuff with not a lot of effect I think. 

[Implementation idea](https://github.com/kris-nova/kubicorn/issues/399#issuecomment-333397923):
>Let's implement `go-prompt` for non-Windows OS-es. It looks very good, and it would be awesome to have something like this for kubicorn.
Here's the my implementation idea:
>1) Add `prompt.go` file to [`cmd`](https://github.com/kris-nova/kubicorn/tree/master/cmd) package which will contain the code.
>2) Add `prompt_windows.go` to [`cmd`](https://github.com/kris-nova/kubicorn/tree/master/cmd) package which will show not available error for Windows.
>3) Instead of defining everything manually, use `cobra` to obtain all commands and flags and build structure like [this](https://github.com/c-bata/kube-prompt/blob/master/kube/completer.go#L31).
>Cobra has many functions for obtaining flags, commands and descriptions, such as [Commands](https://godoc.org/github.com/spf13/cobra#Command.Commands).
>Full cobra docs available @ [godoc](https://godoc.org/github.com/spf13/cobra)
>
>If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/project-walkthrough.html).
>If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

**Comment by xmudrii** [comment]
It looks good, but does we know about portability between terminals and OSes? Would it work good on Windows?

About the completions, we have Bash and ZSH completions. This one looks better, but the I don't see does it work with every shell.

**Comment by MyDigitalLife** [comment]
Good question, looks like windows support is still in the works https://github.com/c-bata/go-prompt/pull/2. We will have to wait unit this works before implementing. We should not kill windows support just for some fancy options.

**Comment by xmudrii** [comment]
Sounds good to me. Let's leave this issue open, it's definitely good idea once they add Windows support. We definitely have at least one Windows user, so it wouldn't be good idea to drop support for it :joy:

**Comment by xmudrii** [comment]
Let's implement `go-prompt` for non-Windows OS-es. It looks very good, and it would be awesome to have something like this for kubicorn.
Here's the my implementation idea:
1) Add `prompt.go` file to `cmd` package which will contain the code.
2) Add `prompt_windows.go` to `cmd` package which will show not available error for Windows.
3) Instead of defining everything manually, use `cobra` to obtain all commands and flags and build structure like [this](https://github.com/c-bata/kube-prompt/blob/master/kube/completer.go#L31).
Cobra has many functions for obtaining flags, commands and descriptions, such as [Commands](https://godoc.org/github.com/spf13/cobra#Command.Commands).
Full cobra docs available @ [godoc](https://godoc.org/github.com/spf13/cobra)

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/projetct-walkthrough.html).
If you have any question, comment on the issue, join or `#kubicorn` channel @ Gophers Slack, or open a PR. We'll always try our best to help you get your PR merged.

I'll update the original issue comment with this info.

**Comment by zoidbergwill** [comment]
I'm having a try at this, will make a WIP PR when I've got something useful.

Busy trying to see if I can generate it similarly to how Cobra generates zsh and bash completions.

**Comment by mohanarpit** [comment]
@xmudrii I just opened a PR #428 for this. Since this is my first contribution to a Golang project, I'd appreciate some feedback on the code quality. If something is not written in idiomatic Go, I'd be happy to change that.
